# Generated by Django 6.0.8 on 2026-08-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'New message'), ('member_added', 'Added to a group or channel'), ('role_changed', 'Role changed')], max_length=20, verbose_name='نوع'),
        ),
    ]
