"""
Django settings for the config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# Every deployment-shaped setting comes from the environment; see .env.example.
# The fallbacks are development-only and must never be relied on in a real run.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-only-insecure-key-change-me')

DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,backend')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # US-9.1 full-text search: SearchVector and GinIndex live here, and both
    # are PostgreSQL-only. architecture.tex chose Postgres over a separate
    # search engine deliberately, so this is the whole of that dependency.
    'django.contrib.postgres',
    'rest_framework',
    'rest_framework_simplejwt',
    # SIMPLE_JWT sets BLACKLIST_AFTER_ROTATION, which needs this app installed.
    'rest_framework_simplejwt.token_blacklist',
    'channels',
    'corsheaders',

    # Domain modules — architecture.tex §5.
    'accounts',
    'messaging',
    'groups_app',
    'channels_app',
    'roles',
    'media_app',
    'notifications',
    'realtime',
    'scheduling',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must sit above CommonMiddleware so preflight responses carry the headers.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'discord'),
        'USER': os.environ.get('POSTGRES_USER', 'discord'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'discord'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media')


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# Token lifetimes.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# RT-01. The channel layer is what carries a group_send from the process that
# published it to every process holding a subscribed socket. InMemoryChannelLayer
# does not cross a process boundary, so with more than one worker a message
# reaches only the clients that happen to share the sender's process — which
# looks like intermittent delivery rather than a missing dependency.
#
# Redis when REDIS_URL is set, in-memory when it is not. The fallback is not a
# convenience: `pytest` runs without the compose stack and a clone that has not
# read the README still has to boot. Anything relying on cross-process fan-out
# has to say so — see realtime/tests/test_channel_layer.py.
REDIS_URL = os.environ.get('REDIS_URL', '')

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
                # A group is one conversation. The default 24h expiry outlives
                # any socket that would read it, and a stale group is a slow
                # leak rather than an error, so it is shortened deliberately.
                'group_expiry': 3600,
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}
    }


# In the container stack nginx puts the SPA and the API on one origin, so CORS
# is not involved. This is for `npm run dev` against a backend on another port.
CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)
CORS_ALLOW_CREDENTIALS = True


# Background jobs — SC-01. RabbitMQ is the broker; task results are not stored
# because scheduling only needs reliable execution, not result retrieval.
CELERY_BROKER_URL = os.environ.get(
    'CELERY_BROKER_URL',
    'amqp://discord:discord@rabbitmq:5672//',
)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_IGNORE_RESULT = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# SC-03 — the beat schedule that runs the dispatcher. Every 60 seconds, so a
# scheduled message is delivered within a minute of its time rather than to the
# second; the composer's copy says "around" for that reason. The task itself
# claims each row conditionally, so a tick that overruns the next one cannot
# double-send.
#
# The card's file list names only `scheduling/tasks.py`, but a beat entry has to
# live in settings and `scheduling/tests/test_celery_config.py` already asserts
# Celery configuration from here. Recorded as a file-list departure in the
# execution plan (deviation 28), the same disclosure C-03 and C-04 made.
CELERY_BEAT_SCHEDULE = {
    'dispatch-due-scheduled-messages': {
        'task': 'scheduling.tasks.dispatch_due_messages',
        'schedule': 60.0,
    },
}
