# Generated by Django 6.0.8 on 2026-08-10 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کانال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کانال')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='channel_avatars/', verbose_name='تصویر کانال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_channels', to=settings.AUTH_USER_MODEL, verbose_name='مالک کانال')),
            ],
            options={
                'verbose_name': 'کانال',
                'verbose_name_plural': 'کانال\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='channels_app.channel', verbose_name='کانال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضو کانال',
                'verbose_name_plural': 'اعضای کانال',
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='unique_channel_membership')],
            },
        ),
    ]
