# Generated by Django 6.0.8 on 2026-08-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0002_channelmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تاپیک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='channels_app.channel', verbose_name='کانال')),
            ],
            options={
                'verbose_name': 'تاپیک',
                'verbose_name_plural': 'تاپیک\u200cها',
                'ordering': ['channel_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'name'), name='unique_topic_name_per_channel')],
            },
        ),
    ]
