# Generated by Django 6.0.8 on 2026-08-10 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نقش')),
                ('can_send_media', models.BooleanField(default=False, verbose_name='ارسال رسانه')),
                ('can_delete_message', models.BooleanField(default=False, verbose_name='حذف پیام دیگران')),
                ('can_create_topic', models.BooleanField(default=False, verbose_name='ایجاد تاپیک')),
                ('can_edit_channel', models.BooleanField(default=False, verbose_name='ویرایش کانال')),
                ('can_remove_member', models.BooleanField(default=False, verbose_name='حذف عضو')),
                ('can_add_member', models.BooleanField(default=False, verbose_name='افزودن عضو')),
                ('can_change_role', models.BooleanField(default=False, verbose_name='تغییر نقش\u200cها')),
                ('can_delete_channel', models.BooleanField(default=False, verbose_name='حذف کانال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='channels_app.channel', verbose_name='کانال')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['channel_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'name'), name='unique_role_name_per_channel')],
            },
        ),
    ]
