# Generated by Django 6.0.8 on 2026-08-11 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0003_topic'),
        ('groups_app', '0001_initial'),
        ('media_app', '0001_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels_app.topic'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('recipient__isnull', False), ('topic__isnull', True)), models.Q(('group__isnull', False), ('recipient__isnull', True), ('topic__isnull', True)), models.Q(('group__isnull', True), ('recipient__isnull', True), ('topic__isnull', False)), _connector='OR'), name='message_has_exactly_one_target'),
        ),
    ]
