# Generated by Django 6.0.8 on 2026-08-12 15:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0003_topic'),
        ('groups_app', '0002_groupmember'),
        ('media_app', '0001_initial'),
        ('messaging', '0003_message_edit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('text', config='simple'), name='message_text_search'),
        ),
    ]
