# Generated by Django 6.0.8 on 2026-08-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_scheduling_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
