# Generated by Django 6.0.7 on 2026-07-28 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات گروه')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='group_avatars/', verbose_name='تصویر گروه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='مدیر گروه')),
                ('members', models.ManyToManyField(related_name='chat_groups', to=settings.AUTH_USER_MODEL, verbose_name='اعضای گروه')),
            ],
        ),
    ]
